### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by drapado** [developer0hye/PyTorch-Darknet53#2]
Hi @developer0hye, great job implementing darknet53!!

I would like to use your model for a custom dataset and I need to do transfer learning. Do you have pre-trained weights of the your model that I can use in mine?

Thank you in advance!

**Comment by developer0hye** [comment]
Sorry, I don't have pre-trained weight file. But I am planning to train as soon as possible.
If training is finished, I will upload this.

**Comment by developer0hye** [comment]
@drapado 
I've uploaded pre-trained weight file now!
