### ISSUE TITLE
Pretrained weights are corrupt

### ISSUE THREAD

**Issue by drkhosravi** [developer0hye/PyTorch-Darknet53#4]
Dear Sir
Please upload pretrained weigths again. I downloaded it twice but its corrupt.

**Comment by developer0hye** [comment]
@drkhosravi Hi!
I think the pre-trained weights contains no problems, check again.
could you show me your error?

**Comment by drkhosravi** [comment]
It cannot be unzipped using WinRAR or other software. The following errors occurs: 
---------------------------
Error
---------------------------
D:\Projects\_Python\Fruit Detection2\model_best.pth.tar
The archive is either in unknown format or damaged
---------------------------
OK   
---------------------------


Sent from Mail for Windows 10

**Comment by developer0hye** [comment]
You don't need to unzip the weight file. You can load the weight without unzip.

**Comment by drkhosravi** [comment]
I also tried so, using the following code:
`model.load_state_dict( torch.load('D:\\Projects\\_Python\\Fruit Detection2\\model_best.pth.tar') )    
`
but another error occures while loading state_dict as illustrated in the figure:

![image](https://user-images.githubusercontent.com/57478245/78330387-1e7a5080-7599-11ea-870c-ad71da318271.png)

**Comment by developer0hye** [comment]
you cannot directly load the weight to model from weight file.
Refer to the training resume part in train.py

**Comment by drkhosravi** [comment]
Solved.
Thank you

**Comment by developer0hye** [comment]
@drkhosravi 
Keep up the good work!
