### ISSUE TITLE
wonder if the pretrained weight file is broken

### ISSUE THREAD

**Issue by korikihaku** [developer0hye/PyTorch-Darknet53#5]
Dear author,
I have downloaded the model_best.pth, but its not able to be opened or extracted. I wonder if the file is broken, if u still have the pretrained weight file, could u plz upload it? plenty of appreciate!

**Comment by developer0hye** [comment]
How do you load the pretrained weight file using python?
Could you show me your code?

**Comment by korikihaku** [comment]
I havent load the file because i was not able to extract the tar
file...both on Windows and Ubuntu environment. Do u have any idea?
Yonghye Kwon <notifications@github.com> 于 2020年5月8日周五 下午11:50写道：

**Comment by developer0hye** [comment]
@korikihaku 
You don't need to extract model file! You can load the model on program without extraction.

**Comment by korikihaku** [comment]
Could you teach me how to load the tar file please..? Much appreciate!

Yonghye Kwon <notifications@github.com> 于 2020年5月9日周六 上午11:42写道：

**Comment by developer0hye** [comment]
```python
model = darknet53(1000)
checkpoint = torch.load(model_path)
model.load_state_dict(checkpoint['state_dict'])
```

**Comment by korikihaku** [comment]
Thanks for your help i will make some try. Thanks a lot !

Yonghye Kwon <notifications@github.com> 于 2020年5月9日周六 下午8:29写道：

**Comment by developer0hye** [comment]
@korikihaku 
I hope your success!
